pipeline{
  agent any  
  stages {
   stage("Opening"){
         steps{
            //Welcome message
            script{
               sh "echo 'Welcome to Jenkins'"
}
}
}

   stage("Workspace_cleanup"){
        //Cleaning WorkSpace
        steps{
            step([$class: 'WsCleanup'])
}
}

   stage("Repo_clone"){
       //Clone repo from GitHub
      steps {
         checkout ([$class: 'GitSCM', branches: [[name: '*/shubham']], userRemoteConfigs: [[credentialsId: 'instance_id', url: 'git@github.com:shubh9975/master.git']]])

}
}

   

   
   stage("static_analysis"){
     //static analysis
      steps{
       script{
       sh '''
            cd infra
            terraform validate 
            cd -
       '''
}
}
}   

}
}
